version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo:
        applies-to: version-updates
        patterns: ["*"]
      cargo-security:
        applies-to: security-updates
        patterns: ["*"]
